sudo: false
language: java
jdk:
- openjdk8
script:
- test/run.sh
notifications:
  slack:
    secure: pigM245rzgPucJbkyza5/6JXLgN4A2i7F/V7JOKNhB7/ZhiZP1pbW1N+SW0lKi+jJMXCyzpBUIgVzUg2gJdTSEGVoqo6lNTYwIDu1um2+zMxTiTC3dyroGz+u0WksRcHkEWF77xhN1xNuDSL9w5Wx+vLPJryIab5SOsp89LvO7NHAo779NB9QfioCsGeDiJ9PfdbOPLWEpwOZx3/M7kiQIC9hdygzW74cjgmwWPLOLDHsghqZ31RC+PwL649jrAmDIf7wFm7KFXpkO7nDb8RAROBrZq+Ii6G9UIbFli8ca9YBK02/15UnD1IEWq2GPX1UHCAL5+IwMVDOYTkQ8fUdR9JqXJEmMIJOYNcYJtt02Pyr5aOBaVIuNr8OqTEUeqXacwAae807PHGmRaX8ymgnU3YbBAs44lN59Gl0gBDJWn6hGQdNi5lVkkAYEXuDjh18ps72TGRSi0CXmqQZPjIQZCnW18v2kiWFiWfg3KqiWr/dj+g3y5K874AisLjen4se2TVG2JdFnEioD8lhrr3cGMLSk1C+1kFHlzkyVuxtYaHYXje1TbCpP/CjIozXi0bWDerhODAKzC6fK/cTpgzIAGyzUYl3nmtnKuwqBqaaFkGk28Iyx6RyhbpM+qmA1BcIPJmZXWx8ZHEToBiasafF63QeslwG1kjYfaqMnMWWw4=
