sudo: false
language: java
jdk:
- openjdk8
script:
- test/run.sh
services:
- rabbitmq
notifications:
  slack:
    secure: fYyNAlqkhPGoJXDckeVaoEJAtf8x5c4lBxmC1DJRee77egFlmSFppZ6xVHsR+Jpa44AxA0vHjkUVO3vEJKxDn0bMGu3sQXs0QmJDIGrHK8Pms759eYLKAj46sWHkpVO1Ot++Szo/A+vubxE2XQIX3gBt7g47R5pS/zuDySCCyNk=
